networks:
  autograder:

services:
  db:
    image: mysql:9.7.0
    command: --lower-case-table-names=1
    profiles:
      - with-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "changeme"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - autograder

  app:
    image: ghcr.io/softwareconstruction240/autograder:latest
    ports:
      - "8080:8080"
    command: ["java", "-Dlog4j2.configurationFile=log4j.properties", "-Dlog4j2.debug=false", "-jar", "/app/target/automatico-1.0-SNAPSHOT.jar",
        "--db-host", "changeme",
        "--db-port", "changeme",
        "--db-name", "changeme",
        "--db-user", "changeme",
        "--db-pass", "changeme",
        "--frontend-url", "changeme",
        "--cas-callback-url", "changeme",
        "--canvas-token", "changeme",
        "--use-canvas", "true",
#        "--disable-compilation", # Enable me, if desired!
        "--client-id", "changeme",
    ]
    networks:
      - autograder

  watchtower:
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    image: containrrr/watchtower
    command: --cleanup

volumes:
    db-data:
